apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8080
  selector:
    service: reverse-proxy
  type: LoadBalancer
