version: "3"
services:
  reverse-proxy:
    build:
      context: .
    image: jiewwantan/udagram-microservice:reverse-proxy1.1
  udagram-restapi-feed:
    build:
      context: ../../udagram-restapi-feed
    image: jiewwantan/udagram-microservice:feed1.1
  udagram-restapi-user:
    build:
      context: ../../udagram-restapi-user
    image: jiewwantan/udagram-microservice:user1.1
  udagram-frontend:
    build:
      context: ../../udagram-frontend
    image: jiewwantan/udagram-microservice:frontend1.1
  